### ISSUE TITLE
unraid 6.10.3安装失败

### ISSUE THREAD

**Issue by thsrite** [ich777/unraid-lxc-plugin#8]
plugin: installing: https://github.com/ich777/unraid-lxc-plugin/raw/master/lxc.plg
plugin: downloading https://github.com/ich777/unraid-lxc-plugin/raw/master/lxc.plg
plugin: downloading: https://github.com/ich777/unraid-lxc-plugin/raw/master/lxc.plg ... done
plugin: downloading: https://github.com/ich777/unraid-lxc-plugin/raw/master/packages/lxc-2022.12.11.txz ... done

+==============================================================================
| Installing new package /boot/config/plugins/lxc/lxc-2022.12.11.txz
+==============================================================================

Verifying package lxc-2022.12.11.txz.
Installing package lxc-2022.12.11.txz:
PACKAGE DESCRIPTION:
Package lxc-2022.12.11.txz installed.
---Something went horribly wrong, can't get latest version from LXC and no local version found!---
Removing package: lxc-2022.12.11
Removing files:
--> Deleting /usr/local/emhttp/plugins/lxc/LXC.page
--> Deleting /usr/local/emhttp/plugins/lxc/LXCAddContainer.page
--> Deleting /usr/local/emhttp/plugins/lxc/LXCCopyContainer.page
--> Deleting /usr/local/emhttp/plugins/lxc/LXCGuide.page
--> Deleting /usr/local/emhttp/plugins/lxc/LXCRestoreSnapshot.page
--> Deleting /usr/local/emhttp/plugins/lxc/LXCSettings.page
--> Deleting /usr/local/emhttp/plugins/lxc/LXCSnapshots.page
--> Deleting /usr/local/emhttp/plugins/lxc/css/lxc.css
--> Deleting /usr/local/emhttp/plugins/lxc/event/disks_mounted
--> Deleting /usr/local/emhttp/plugins/lxc/event/unmounting_disks
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/almalinux.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/alpine.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/alt.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/amazonlinux.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/apertis.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/archlinux.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/busybox.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/centos.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/debian.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/devuan.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/fedora.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/funtoo.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/gentoo.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/kali.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/mint.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/opensuse.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/opnwrt.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/oracle.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/plamo.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/pld.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/rockylinux.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/springdalelinux.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/ubuntu.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/distributions/voidlinux.png
--> Deleting /usr/local/emhttp/plugins/lxc/images/lxc.png
--> Deleting /usr/local/emhttp/plugins/lxc/include/Container.php
--> Deleting /usr/local/emhttp/plugins/lxc/include/Settings.php
--> Deleting /usr/local/emhttp/plugins/lxc/include/Snapshot.php
--> Deleting /usr/local/emhttp/plugins/lxc/include/ajax.php
--> Deleting /usr/local/emhttp/plugins/lxc/include/create_vnc_container.sh
--> Deleting /usr/local/emhttp/plugins/lxc/include/functions.php
--> Deleting /usr/local/emhttp/plugins/lxc/js/lxc.js
--> Deleting empty directory /usr/local/emhttp/plugins/lxc/js/
--> Deleting empty directory /usr/local/emhttp/plugins/lxc/include/
--> Deleting empty directory /usr/local/emhttp/plugins/lxc/images/distributions/
--> Deleting empty directory /usr/local/emhttp/plugins/lxc/images/
--> Deleting empty directory /usr/local/emhttp/plugins/lxc/event/
--> Deleting empty directory /usr/local/emhttp/plugins/lxc/css/
WARNING: Unique directory /usr/local/emhttp/plugins/lxc/ contains new files
plugin: run failed: /bin/bash retval: 1

正在更新支持链接

**Comment by ich777** [comment]
> ---Something went horribly wrong, can't get latest version from LXC and no local version found!---

I assume you are based in China?
This is maybe caused because it can't properly can't communicate with GitHub.
What the plugin ultimately tries is to download this package from over [here](https://github.com/ich777/unraid-lxc-plugin/releases/tag/5.0.1) or better speaking it can't properly communicate with GitHub API to determine the version and download the package afterwards.

You have now a few solutions to this:

1. Try it a few times until it is working (some users over there said that it started working after a few tries, but please be aware that you should wait always about 30 minutes between you try to install it).
2. Download the package manually and create the folder structure manually on your USB Boot device and place the downloaded package in the right location, after that install the plugin as usual (then it will find the package locally and install it).


If you choose the second way create the folder `/boot/config/plugins/lxc/packages`, place the downloaded package from [here](https://github.com/ich777/unraid-lxc-plugin/releases/download/5.0.1/LXC-5.0.1-1.txz) in the created folder and install the plugin again from the CA App.

Hope that helps.

**Comment by thsrite** [comment]
| Installing new package /boot/config/plugins/lxc/lxc-2022.12.11.txz
+==============================================================================

Verifying package lxc-2022.12.11.txz.
Installing package lxc-2022.12.11.txz:
PACKAGE DESCRIPTION:
Package lxc-2022.12.11.txz installed.

--------LXC Package found locally, installing...--------
---------------LXC installation complete!---------------
plugin: lxc.plg installed



Thank you. I have solved it！！！
